# Generated by Django 5.0 on 2023-12-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Space4Wheels', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pending_approval',
            field=models.BooleanField(default=True),
        ),
    ]
