# Generated by Django 5.0 on 2023-12-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Space4Wheels', '0005_booking_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='overall_rating',
            field=models.FloatField(default=0),
        ),
    ]
