# Generated by Django 5.0 on 2023-12-19 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Space4Wheels', '0008_renterrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RenterRating',
        ),
    ]
